// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlVoYJDdvOUvvJ7xb8r0nyt6ETZbb-944',
    appId: '1:124824593205:web:PLACEHOLDER',
    messagingSenderId: '124824593205',
    projectId: 'alien-hologram-470217-r0',
    authDomain: 'alien-hologram-470217-r0.firebaseapp.com',
    storageBucket: 'alien-hologram-470217-r0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVoYJDdvOUvvJ7xb8r0nyt6ETZbb-944',
    appId: '1:124824593205:android:e470210f7eba41e80aa27c',
    messagingSenderId: '124824593205',
    projectId: 'alien-hologram-470217-r0',
    storageBucket: 'alien-hologram-470217-r0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlVoYJDdvOUvvJ7xb8r0nyt6ETZbb-944',
    appId: '1:124824593205:ios:PLACEHOLDER',
    messagingSenderId: '124824593205',
    projectId: 'alien-hologram-470217-r0',
    storageBucket: 'alien-hologram-470217-r0.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlVoYJDdvOUvvJ7xb8r0nyt6ETZbb-944',
    appId: '1:124824593205:ios:PLACEHOLDER',
    messagingSenderId: '124824593205',
    projectId: 'alien-hologram-470217-r0',
    storageBucket: 'alien-hologram-470217-r0.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlVoYJDdvOUvvJ7xb8r0nyt6ETZbb-944',
    appId: '1:124824593205:web:PLACEHOLDER',
    messagingSenderId: '124824593205',
    projectId: 'alien-hologram-470217-r0',
    authDomain: 'alien-hologram-470217-r0.firebaseapp.com',
    storageBucket: 'alien-hologram-470217-r0.firebasestorage.app',
  );

}