// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNRSaW1gjY1CLS7iWgqbUEy1JeUMD12dw',
    appId: '1:179822847007:web:1785448f95d82cc711a12a',
    messagingSenderId: '179822847007',
    projectId: 'datacollection-e8170',
    authDomain: 'datacollection-e8170.firebaseapp.com',
    storageBucket: 'datacollection-e8170.firebasestorage.app',
    measurementId: 'G-3X0T1TQM3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEP7xS5_u_Co3kJfoPjOXUilcNq7dfMw',
    appId: '1:179822847007:android:41769428ba1e044a11a12a',
    messagingSenderId: '179822847007',
    projectId: 'datacollection-e8170',
    storageBucket: 'datacollection-e8170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeuySPMsZS6rmRM-C01xxF7mAkG75HX74',
    appId: '1:179822847007:ios:167e3d896367458511a12a',
    messagingSenderId: '179822847007',
    projectId: 'datacollection-e8170',
    storageBucket: 'datacollection-e8170.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeuySPMsZS6rmRM-C01xxF7mAkG75HX74',
    appId: '1:179822847007:ios:167e3d896367458511a12a',
    messagingSenderId: '179822847007',
    projectId: 'datacollection-e8170',
    storageBucket: 'datacollection-e8170.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNRSaW1gjY1CLS7iWgqbUEy1JeUMD12dw',
    appId: '1:179822847007:web:316b5bee4c7009ce11a12a',
    messagingSenderId: '179822847007',
    projectId: 'datacollection-e8170',
    authDomain: 'datacollection-e8170.firebaseapp.com',
    storageBucket: 'datacollection-e8170.firebasestorage.app',
    measurementId: 'G-EWTYLL22ZF',
  );

}